#include "xprof/frontend/app/components/trace_viewer_v2/color/color_generator.h"

#include <vector>

#include "xprof/frontend/app/components/trace_viewer_v2/color/colors.h"
#include "absl/base/no_destructor.h"
#include "absl/strings/string_view.h"
#include "third_party/dear_imgui/imgui.h"
#include "util/hash/highway_fingerprint.h"

namespace traceviewer {

namespace {

static constexpr ImU32 event_colors[] = {
    kMaterialPurple70,
    kMaterialGreen80,
    kMaterialBlue80,
    kMaterialYellow90,
};

// Generates colors based on string IDs.
// The color is generated by hashing the ID and picking a color from a
// predefined list.
class ColorGenerator {
 public:
  ColorGenerator(const ColorGenerator&) = delete;
  ColorGenerator& operator=(const ColorGenerator&) = delete;
  ColorGenerator(ColorGenerator&&) = delete;
  ColorGenerator& operator=(ColorGenerator&&) = delete;

  // Returns a color for the given ID.
  ImU32 ColorForId(absl::string_view id) {
    return event_colors[util_hash::HighwayFingerprint64(id) %
                        std::size(event_colors)];
  }

 private:
  friend class absl::NoDestructor<ColorGenerator>;
  ColorGenerator() = default;
};

}  // namespace

// Generates a color for a given string ID.
// The color is generated by hashing the ID and picking a color from a
// predefined list.
ImU32 GetColorForId(absl::string_view id) {
  static absl::NoDestructor<ColorGenerator> generator;
  return generator->ColorForId(id);
}

}  // namespace traceviewer
