exports_files(
    ["tpu_input_pipeline_analysis_constants.cc"],
    visibility = ["@org_xprof//xprof/convert:__pkg__"],
)

exports_files(
    ["url_utils.cc"],
    visibility = ["@org_xprof//xprof/convert:__pkg__"],
)
