#ifndef THIRD_PARTY_XPROF_UTILS_TPU_COUNTER_IDS_H_
#define THIRD_PARTY_XPROF_UTILS_TPU_COUNTER_IDS_H_

#include <cstdint>

namespace xprof {

// Enum of TPU counter IDs used in
// perftools/gputools/profiler/collector/tpu_counter_util.cc.
// This is a best-effort list generated without macro expansion and might be
// incomplete.
enum TpuCounterIdsTpu7x : uint64_t {
  // NOLINTBEGIN
  VF_CHIP_DIE0_PWRMGR_PWRMGR_TC_THROTTLE_CORE_DEBUG_STATS_UNPRIVILEGED_CLOCKS_SKIPPED =
      2847490064,
  VF_CHIP_DIE0_PWRMGR_PWRMGR_TC_THROTTLE_CORE_DEBUG_STATS_UNPRIVILEGED_CYCLE_COUNT =
      2847490056,
  VF_CHIP_DIE0_PWRMGR_PWRMGR_TC_THROTTLE_CORE_DEBUG_STATS_UNPRIVILEGED_EXT_THROTTLE_CLOCKS_SKIPPED =
      2847490088,
  VF_CHIP_DIE0_PWRMGR_PWRMGR_TC_THROTTLE_CORE_DEBUG_STATS_UNPRIVILEGED_LDIDT_DROOP_CLOCKS_SKIPPED =
      2847490112,
  VF_CHIP_DIE0_TC_TCS_TC_MISC_TCS_STATS_TCS_STATS_COUNTERS_UNPRIVILEGED_COUNT_CYCLES =
      2791874568,
  VF_CHIP_DIE0_TC_TCS_TC_MISC_TCS_STATS_TCS_STATS_COUNTERS_UNPRIVILEGED_COUNT_MATMUL_LMR_BF16_MXU_0 =
      2791875000,
  VF_CHIP_DIE0_TC_TCS_TC_MISC_TCS_STATS_TCS_STATS_COUNTERS_UNPRIVILEGED_COUNT_MATMUL_LMR_BF16_MXU_1 =
      2791875008,
  VF_CHIP_DIE0_TC_TCS_TC_MISC_TCS_STATS_TCS_STATS_COUNTERS_UNPRIVILEGED_COUNT_MATMUL_VREG_BF16_MXU_0 =
      2791874968,
  VF_CHIP_DIE0_TC_TCS_TC_MISC_TCS_STATS_TCS_STATS_COUNTERS_UNPRIVILEGED_COUNT_MATMUL_VREG_BF16_MXU_1 =
      2791874976,
  VF_CHIP_DIE0_TC_TCS_TC_MISC_TCS_STATS_TCS_STATS_COUNTERS_UNPRIVILEGED_COUNT_MATMUL_VREG_F32_MXU_0 =
      2791874952,
  VF_CHIP_DIE0_TC_TCS_TC_MISC_TCS_STATS_TCS_STATS_COUNTERS_UNPRIVILEGED_COUNT_MATMUL_VREG_F32_MXU_1 =
      2791874960,
  VF_CHIP_DIE0_TC_TCS_TC_MISC_TCS_STATS_TCS_STATS_COUNTERS_UNPRIVILEGED_COUNT_MATMUL_VREG_F8_MXU_0 =
      2791874984,
  VF_CHIP_DIE0_TC_TCS_TC_MISC_TCS_STATS_TCS_STATS_COUNTERS_UNPRIVILEGED_COUNT_MATMUL_VREG_F8_MXU_1 =
      2791874992,
  VF_CHIP_DIE0_TC_TCS_TC_MISC_TCS_STATS_TCS_STATS_COUNTERS_UNPRIVILEGED_COUNT_MATPUSH_CYCLES_MXU_0 =
      2791875056,
  VF_CHIP_DIE0_TC_TCS_TC_MISC_TCS_STATS_TCS_STATS_COUNTERS_UNPRIVILEGED_COUNT_MATPUSH_CYCLES_MXU_1 =
      2791875064,
  VF_CHIP_DIE0_TC_TCS_TC_MISC_TCS_STATS_TCS_STATS_COUNTERS_UNPRIVILEGED_COUNT_MXU_BUSY_0 =
      2791875016,
  VF_CHIP_DIE0_TC_TCS_TC_MISC_TCS_STATS_TCS_STATS_COUNTERS_UNPRIVILEGED_COUNT_MXU_BUSY_1 =
      2791875024,
  VF_CHIP_DIE0_TC_TCS_TC_MISC_TCS_STATS_TCS_STATS_COUNTERS_UNPRIVILEGED_COUNT_MXU_BUSY_2 =
      2791875032,
  VF_CHIP_DIE0_TC_TCS_TC_MISC_TCS_STATS_TCS_STATS_COUNTERS_UNPRIVILEGED_COUNT_PACKED_XLU_0 =
      2791875136,
  VF_CHIP_DIE0_TC_TCS_TC_MISC_TCS_STATS_TCS_STATS_COUNTERS_UNPRIVILEGED_COUNT_PACKED_XLU_1 =
      2791875144,
  VF_CHIP_DIE0_TC_TCS_TC_MISC_TCS_STATS_TCS_STATS_COUNTERS_UNPRIVILEGED_COUNT_ROTATE_PERMUTE_INSTRUCTION_XLU_0 =
      2791875088,
  VF_CHIP_DIE0_TC_TCS_TC_MISC_TCS_STATS_TCS_STATS_COUNTERS_UNPRIVILEGED_COUNT_ROTATE_PERMUTE_INSTRUCTION_XLU_1 =
      2791875096,
  VF_CHIP_DIE0_TC_TCS_TC_MISC_TCS_STATS_TCS_STATS_COUNTERS_UNPRIVILEGED_COUNT_ROTATE_PERMUTE_SET_INSTRUCTION_XLU_0 =
      2791875104,
  VF_CHIP_DIE0_TC_TCS_TC_MISC_TCS_STATS_TCS_STATS_COUNTERS_UNPRIVILEGED_COUNT_ROTATE_PERMUTE_SET_INSTRUCTION_XLU_1 =
      2791875112,
  VF_CHIP_DIE0_TC_TCS_TC_MISC_TCS_STATS_TCS_STATS_COUNTERS_UNPRIVILEGED_COUNT_SCALAR_ALU_INSTRUCTION_0 =
      2791874648,
  VF_CHIP_DIE0_TC_TCS_TC_MISC_TCS_STATS_TCS_STATS_COUNTERS_UNPRIVILEGED_COUNT_SCALAR_ALU_INSTRUCTION_1 =
      2791874656,
  VF_CHIP_DIE0_TC_TCS_TC_MISC_TCS_STATS_TCS_STATS_COUNTERS_UNPRIVILEGED_COUNT_TRANSPOSE_XLU_0 =
      2791875120,
  VF_CHIP_DIE0_TC_TCS_TC_MISC_TCS_STATS_TCS_STATS_COUNTERS_UNPRIVILEGED_COUNT_TRANSPOSE_XLU_1 =
      2791875128,
  VF_CHIP_DIE0_TC_TCS_TC_MISC_TCS_STATS_TCS_STATS_COUNTERS_UNPRIVILEGED_COUNT_VECTOR_ALU_INSTRUCTION_0 =
      2791874816,
  VF_CHIP_DIE0_TC_TCS_TC_MISC_TCS_STATS_TCS_STATS_COUNTERS_UNPRIVILEGED_COUNT_VECTOR_ALU_INSTRUCTION_1 =
      2791874824,
  VF_CHIP_DIE0_TC_TCS_TC_MISC_TCS_STATS_TCS_STATS_COUNTERS_UNPRIVILEGED_COUNT_VECTOR_ALU_INSTRUCTION_2 =
      2791874832,
  VF_CHIP_DIE0_TC_TCS_TC_MISC_TCS_STATS_TCS_STATS_COUNTERS_UNPRIVILEGED_COUNT_VECTOR_ALU_INSTRUCTION_3 =
      2791874840,
  VF_CHIP_DIE0_TC_TCS_TC_MISC_TCS_STATS_TCS_STATS_COUNTERS_UNPRIVILEGED_COUNT_VLD_INSTRUCTION_0 =
      2791874864,
  VF_CHIP_DIE0_TC_TCS_TC_MISC_TCS_STATS_TCS_STATS_COUNTERS_UNPRIVILEGED_COUNT_VLD_INSTRUCTION_1 =
      2791874872,
  VF_CHIP_DIE0_TC_TCS_TC_MISC_TCS_STATS_TCS_STATS_COUNTERS_UNPRIVILEGED_COUNT_VST_INSTRUCTION =
      2791874848,
  VF_CHIP_DIE0_TC_TCS_TC_MISC_TCS_STATS_TCS_STATS_COUNTERS_UNPRIVILEGED_COUNT_XLU_BUSY_0 =
      2791875152,
  VF_CHIP_DIE0_TC_TCS_TC_MISC_TCS_STATS_TCS_STATS_COUNTERS_UNPRIVILEGED_COUNT_XLU_BUSY_1 =
      2791875160,
  VF_CHIP_DIE0_TC_TCS_TC_MISC_TCS_STATS_TCS_STATS_COUNTERS_UNPRIVILEGED_COUNT_XLU_BUSY_2 =
      2791875168,
  VF_CHIP_DIE1_PWRMGR_PWRMGR_TC_THROTTLE_CORE_DEBUG_STATS_UNPRIVILEGED_CLOCKS_SKIPPED =
      3384360976,
  VF_CHIP_DIE1_PWRMGR_PWRMGR_TC_THROTTLE_CORE_DEBUG_STATS_UNPRIVILEGED_CYCLE_COUNT =
      3384360968,
  VF_CHIP_DIE1_PWRMGR_PWRMGR_TC_THROTTLE_CORE_DEBUG_STATS_UNPRIVILEGED_EXT_THROTTLE_CLOCKS_SKIPPED =
      3384361000,
  VF_CHIP_DIE1_PWRMGR_PWRMGR_TC_THROTTLE_CORE_DEBUG_STATS_UNPRIVILEGED_LDIDT_DROOP_CLOCKS_SKIPPED =
      3384361024,
  VF_CHIP_DIE1_TC_TCS_TC_MISC_TCS_STATS_TCS_STATS_COUNTERS_UNPRIVILEGED_COUNT_CYCLES =
      3328745480,
  VF_CHIP_DIE1_TC_TCS_TC_MISC_TCS_STATS_TCS_STATS_COUNTERS_UNPRIVILEGED_COUNT_MATMUL_LMR_BF16_MXU_0 =
      3328745912,
  VF_CHIP_DIE1_TC_TCS_TC_MISC_TCS_STATS_TCS_STATS_COUNTERS_UNPRIVILEGED_COUNT_MATMUL_LMR_BF16_MXU_1 =
      3328745920,
  VF_CHIP_DIE1_TC_TCS_TC_MISC_TCS_STATS_TCS_STATS_COUNTERS_UNPRIVILEGED_COUNT_MATMUL_VREG_BF16_MXU_0 =
      3328745880,
  VF_CHIP_DIE1_TC_TCS_TC_MISC_TCS_STATS_TCS_STATS_COUNTERS_UNPRIVILEGED_COUNT_MATMUL_VREG_BF16_MXU_1 =
      3328745888,
  VF_CHIP_DIE1_TC_TCS_TC_MISC_TCS_STATS_TCS_STATS_COUNTERS_UNPRIVILEGED_COUNT_MATMUL_VREG_F32_MXU_0 =
      3328745864,
  VF_CHIP_DIE1_TC_TCS_TC_MISC_TCS_STATS_TCS_STATS_COUNTERS_UNPRIVILEGED_COUNT_MATMUL_VREG_F32_MXU_1 =
      3328745872,
  VF_CHIP_DIE1_TC_TCS_TC_MISC_TCS_STATS_TCS_STATS_COUNTERS_UNPRIVILEGED_COUNT_MATMUL_VREG_F8_MXU_0 =
      3328745896,
  VF_CHIP_DIE1_TC_TCS_TC_MISC_TCS_STATS_TCS_STATS_COUNTERS_UNPRIVILEGED_COUNT_MATMUL_VREG_F8_MXU_1 =
      3328745904,
  VF_CHIP_DIE1_TC_TCS_TC_MISC_TCS_STATS_TCS_STATS_COUNTERS_UNPRIVILEGED_COUNT_MATPUSH_CYCLES_MXU_0 =
      3328745968,
  VF_CHIP_DIE1_TC_TCS_TC_MISC_TCS_STATS_TCS_STATS_COUNTERS_UNPRIVILEGED_COUNT_MATPUSH_CYCLES_MXU_1 =
      3328745976,
  VF_CHIP_DIE1_TC_TCS_TC_MISC_TCS_STATS_TCS_STATS_COUNTERS_UNPRIVILEGED_COUNT_MXU_BUSY_0 =
      3328745928,
  VF_CHIP_DIE1_TC_TCS_TC_MISC_TCS_STATS_TCS_STATS_COUNTERS_UNPRIVILEGED_COUNT_MXU_BUSY_1 =
      3328745936,
  VF_CHIP_DIE1_TC_TCS_TC_MISC_TCS_STATS_TCS_STATS_COUNTERS_UNPRIVILEGED_COUNT_MXU_BUSY_2 =
      3328745944,
  VF_CHIP_DIE1_TC_TCS_TC_MISC_TCS_STATS_TCS_STATS_COUNTERS_UNPRIVILEGED_COUNT_PACKED_XLU_0 =
      3328746048,
  VF_CHIP_DIE1_TC_TCS_TC_MISC_TCS_STATS_TCS_STATS_COUNTERS_UNPRIVILEGED_COUNT_PACKED_XLU_1 =
      3328746056,
  VF_CHIP_DIE1_TC_TCS_TC_MISC_TCS_STATS_TCS_STATS_COUNTERS_UNPRIVILEGED_COUNT_ROTATE_PERMUTE_INSTRUCTION_XLU_0 =
      3328746000,
  VF_CHIP_DIE1_TC_TCS_TC_MISC_TCS_STATS_TCS_STATS_COUNTERS_UNPRIVILEGED_COUNT_ROTATE_PERMUTE_INSTRUCTION_XLU_1 =
      3328746008,
  VF_CHIP_DIE1_TC_TCS_TC_MISC_TCS_STATS_TCS_STATS_COUNTERS_UNPRIVILEGED_COUNT_ROTATE_PERMUTE_SET_INSTRUCTION_XLU_0 =
      3328746016,
  VF_CHIP_DIE1_TC_TCS_TC_MISC_TCS_STATS_TCS_STATS_COUNTERS_UNPRIVILEGED_COUNT_ROTATE_PERMUTE_SET_INSTRUCTION_XLU_1 =
      3328746024,
  VF_CHIP_DIE1_TC_TCS_TC_MISC_TCS_STATS_TCS_STATS_COUNTERS_UNPRIVILEGED_COUNT_SCALAR_ALU_INSTRUCTION_0 =
      3328745560,
  VF_CHIP_DIE1_TC_TCS_TC_MISC_TCS_STATS_TCS_STATS_COUNTERS_UNPRIVILEGED_COUNT_SCALAR_ALU_INSTRUCTION_1 =
      3328745568,
  VF_CHIP_DIE1_TC_TCS_TC_MISC_TCS_STATS_TCS_STATS_COUNTERS_UNPRIVILEGED_COUNT_TRANSPOSE_XLU_0 =
      3328746032,
  VF_CHIP_DIE1_TC_TCS_TC_MISC_TCS_STATS_TCS_STATS_COUNTERS_UNPRIVILEGED_COUNT_TRANSPOSE_XLU_1 =
      3328746040,
  VF_CHIP_DIE1_TC_TCS_TC_MISC_TCS_STATS_TCS_STATS_COUNTERS_UNPRIVILEGED_COUNT_VECTOR_ALU_INSTRUCTION_0 =
      3328745728,
  VF_CHIP_DIE1_TC_TCS_TC_MISC_TCS_STATS_TCS_STATS_COUNTERS_UNPRIVILEGED_COUNT_VECTOR_ALU_INSTRUCTION_1 =
      3328745736,
  VF_CHIP_DIE1_TC_TCS_TC_MISC_TCS_STATS_TCS_STATS_COUNTERS_UNPRIVILEGED_COUNT_VECTOR_ALU_INSTRUCTION_2 =
      3328745744,
  VF_CHIP_DIE1_TC_TCS_TC_MISC_TCS_STATS_TCS_STATS_COUNTERS_UNPRIVILEGED_COUNT_VECTOR_ALU_INSTRUCTION_3 =
      3328745752,
  VF_CHIP_DIE1_TC_TCS_TC_MISC_TCS_STATS_TCS_STATS_COUNTERS_UNPRIVILEGED_COUNT_VLD_INSTRUCTION_0 =
      3328745776,
  VF_CHIP_DIE1_TC_TCS_TC_MISC_TCS_STATS_TCS_STATS_COUNTERS_UNPRIVILEGED_COUNT_VLD_INSTRUCTION_1 =
      3328745784,
  VF_CHIP_DIE1_TC_TCS_TC_MISC_TCS_STATS_TCS_STATS_COUNTERS_UNPRIVILEGED_COUNT_VST_INSTRUCTION =
      3328745760,
  VF_CHIP_DIE1_TC_TCS_TC_MISC_TCS_STATS_TCS_STATS_COUNTERS_UNPRIVILEGED_COUNT_XLU_BUSY_0 =
      3328746064,
  VF_CHIP_DIE1_TC_TCS_TC_MISC_TCS_STATS_TCS_STATS_COUNTERS_UNPRIVILEGED_COUNT_XLU_BUSY_1 =
      3328746072,
  VF_CHIP_DIE1_TC_TCS_TC_MISC_TCS_STATS_TCS_STATS_COUNTERS_UNPRIVILEGED_COUNT_XLU_BUSY_2 =
      3328746080,
  // NOLINTEND
};

}  // namespace xprof

#endif  // THIRD_PARTY_XPROF_UTILS_TPU_COUNTER_IDS_H_
