load("@npm//@bazel/concatjs:index.bzl", "ts_library")

package(default_visibility = ["@org_xprof//frontend:__subpackages__"])

ts_library(
    name = "classes",
    srcs = [
        "throbber.ts",
    ],
    deps = [
        "@org_xprof//frontend/app/common/interfaces",
    ],
)
